### PR TITLE
Update patch.sh

### PR DESCRIPTION
**Pull request by antonyzhao**
also frameworks-in-app need to be signed when signing-app-bin

### CODE REVIEW

**Comment by Naituw** [comment]
Hi, @antonyzhao 

Seems like your commit loses tab indents, would you fix that so I can focus on code that actual changed?

**Comment by antonyzhao** [comment]
ok, sorry for that.
```
echo "Code Signing Frameworks"
if [ -d "$TARGET_APP_FRAMEWORKS_PATH" ]; then
for FRAMEWORK in "$TARGET_APP_FRAMEWORKS_PATH/"*
do
FILENAME=$(basename $FRAMEWORK)
/usr/bin/codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" "$FRAMEWORK"
done
fi
```
just put the code before sign app bin

**Comment by Naituw** [comment]
I think current script already sign all the frameworks, did I miss something?

**Comment by antonyzhao** [comment]
看到你的那行代码了，你是先创建的路径:
```
mkdir -p "$TARGET_APP_FRAMEWORKS_PATH"
```
,这个路径位于
```
TARGET_APP_FRAMEWORKS_PATH="$BUILT_PRODUCTS_DIR/$TARGET_NAME.app/Frameworks"
```
之后执行的
```   
 "$OPTOOL" install -c load -p "@executable_path/Frameworks/$file/$filename" -t "$TARGET_APP_PATH/$APP_BINARY"
```
，问题是，如果ipa包中已经包含了framework的话，这儿并没有执行sign的操作，因为sign的对象都位于
```
TARGET_APP_FRAMEWORKS_PATH 
```
这个路径中，是不包含ipa文件自身所依赖的framework的。
另外，不好意思，上面代码发错了，发的是你自己的，见下面：
```
for framework in `ls $TARGET_APP_PATH | grep framework`
do
    echo 'framework is '$framework
    /usr/bin/codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" --no-strict $TARGET_APP_PATH/${framework}
done
```

**Comment by Naituw** [comment]
`TARGET_APP_FRAMEWORKS_PATH` is the default folder for private frameworks, so it will work for most apps. 

But I think there may have cases where frameworks not located in `Frameworks` folder, so I assume your approach (to find every framework in bundle) is better...

The commit still have some issues need to fix before I can merge:
- `ls $TARGET_APP_PATH | grep framework` doesn't seems to support frameworks inside sub-folders, which will failed to sign `Frameworks/*.framework`
- Missing tab indents
- A more specific/detailed commit message is appreciated

**Pull request closed without merging**
